version: "3.8"
services:
  nodeserver:
    build:
        context: ./app
    container_name: node-server
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh < com erro - nao consegui corrigir >
    image: maurper/node-p
    ports:
      - "3000:3000"
    networks:
      - node-network

  nginx:
    build:
        context: ./nginx
    container_name: nginx-server
    image: maurper/nginx-p
    restart: always
    ports:
      - "8080:80"
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=passuser
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - node-network

networks:
  node-network:
    driver: bridge